### ISSUE TITLE
Integrate server uptime monitoring with Slack

### ISSUE THREAD

**Issue by nanjiangshu** [NBISweden/libpredweb#11]
As a developer, I want the uptime monitoring of web-servers integrate to Slack so that every team member can see the status these web-servers. 

List of web-servers to be monitored:

https://topcons.net
https://proq3.bioinfo.se 
https://subcons.bioinfo.se 
https://scampi.bioinfo.se
https://b2.topcons.net 
https://prodres.bioinfo.se
https://pconsc3.bioinfo.se

**Comment by MalinAhlberg** [comment]
I suggest we use https://uptimerobot.com/. That gives us notifications if 
Should we also create a special slack channel for this?

**Comment by MalinAhlberg** [comment]
I have set up the uptimerobot to watch all web servers and notify #protein-prediction. The uptimerobot account is using my email, though, should I change that? In that case to what email? @nanjiangshu

**Comment by nanjiangshu** [comment]
Thanks very much @MalinAhlberg. It's fine with your email. I think this issue can be closed.

**Comment by MalinAhlberg** [comment]
For some reason the estimate menu is not available for me on this board. But I would say it was a 1.

**Comment by nanjiangshu** [comment]
I find the status of invites is pending, maybe this is the reason?

**Comment by MalinAhlberg** [comment]
I don't think I can see that either :thinking:

**Comment by nanjiangshu** [comment]
But you do get email notification of this message, right? If so, that email should already been joined.

**Comment by MalinAhlberg** [comment]
I do! So something is working :)
